name: Metrics
on:
  # Schedule updates every 12 hours
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below allow you to run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token stored in Secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: angadkumar28
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # Visual Fixes
          config_padding: 0, 8 + 10%
          config_display: large
          plugins_errors_fatal: no
          
          # Achievements Plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # Languages Plugin
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Habits Plugin
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Isocalendar (3D Contribution View)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Lines of code plugin
          plugin_lines: yes
